language: python

sudo: false

cache:
  - pip

install:
  - pip install simplejson

script:
  - python checkjson.py && python coverage.py | sort -n

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
