language: python

dist: trusty
sudo: false
group: beta


script:
  - ./EOL.py rmd/*.json
  - python checkjson.py && ./coverage.sh
  - ./tidy-json.py && git diff --exit-code

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
